# Generated by Django 6.0.5 on 2026-05-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=100, verbose_name='Ayar Anahtarı (örn: Email)')),
                ('value', models.CharField(max_length=254, verbose_name='Ayar Değeri')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200, verbose_name='Proje Başlığı')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Görsel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık (örn: Junior SAP Consultant)')),
                ('date', models.CharField(max_length=100, verbose_name='Tarih Aralığı')),
                ('content', models.TextField(verbose_name='Açıklama/Detay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(max_length=100, verbose_name='Platform (Github, LinkedIn)')),
                ('url', models.URLField(verbose_name='Link')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
