# Generated by Django 6.0.5 on 2026-05-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('badge_text', models.CharField(default='Beni Tanıyın', max_length=100, verbose_name='Rozet Metni')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('paragraph_1', models.TextField(verbose_name='1. Paragraf')),
                ('paragraph_2', models.TextField(blank=True, default='', verbose_name='2. Paragraf')),
            ],
            options={
                'verbose_name': 'Hakkımda Bölümü',
                'verbose_name_plural': 'Hakkımda Bölümü',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(max_length=200, verbose_name='Sağlayıcı (örn: Cisco)')),
                ('name', models.CharField(max_length=200, verbose_name='Sertifika Adı')),
                ('date', models.CharField(max_length=100, verbose_name='Tarih')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Sertifika',
                'verbose_name_plural': 'Sertifikalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('icon_class', models.CharField(default='bi bi-info-circle', help_text='Bootstrap Icons sınıfı. Örn: bi bi-envelope', max_length=100, verbose_name='İkon Sınıfı')),
                ('label', models.CharField(max_length=100, verbose_name='Etiket (örn: Email Adresi)')),
                ('value', models.CharField(max_length=254, verbose_name='Değer')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'İletişim Bilgisi',
                'verbose_name_plural': 'İletişim Bilgileri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200, verbose_name='Bölüm / Program')),
                ('date_range', models.CharField(max_length=100, verbose_name='Tarih Aralığı')),
                ('institution', models.CharField(max_length=200, verbose_name='Kurum / Üniversite')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitimler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200, verbose_name='Pozisyon')),
                ('date_range', models.CharField(max_length=100, verbose_name='Tarih Aralığı')),
                ('company', models.CharField(max_length=200, verbose_name='Şirket')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Konum')),
                ('bullets', models.TextField(help_text='Her satır bir madde olarak gösterilecek.', verbose_name='Maddeler')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'İş Deneyimi',
                'verbose_name_plural': 'İş Deneyimleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='İsim (Büyük başlık)')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Alt Başlık (h2)')),
                ('typed_titles', models.CharField(help_text='Virgülle ayırarak yazın. Örn: SAP Danışmanı, Full-Stack Developer', max_length=500, verbose_name='Yazı Animasyonu Başlıkları')),
                ('description', models.TextField(verbose_name='Açıklama Metni')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Profil Fotoğrafı')),
            ],
            options={
                'verbose_name': 'Hero Bölümü',
                'verbose_name_plural': 'Hero Bölümü',
            },
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'verbose_name': 'Genel Ayar', 'verbose_name_plural': 'Genel Ayarlar'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['order'], 'verbose_name': 'Sosyal Link', 'verbose_name_plural': 'Sosyal Linkler'},
        ),
        migrations.AddField(
            model_name='project',
            name='filter_tag',
            field=models.CharField(default='filter-web', help_text='CSS sınıfı. Örn: filter-web, filter-sap', max_length=50, verbose_name='Filtre Etiketi'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_description',
            field=models.TextField(blank=True, default='', verbose_name='Teknik Detay'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(default='bi bi-link', help_text='Bootstrap Icons sınıfı. Örn: bi bi-github', max_length=100, verbose_name='İkon Sınıfı'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Kısa Açıklama'),
        ),
    ]
